### ISSUE TITLE
Study 관련 오류 및 버그 수정

### ISSUE THREAD

**Issue by jootang2** [likelion-backendschool/ZZANDI#100]
Study 관련 오류 및 버그 수정

# Todo
- [x] Study 수정 시 빈 값이 있는 경우 오류 => Form과 마찬가지로 에러메세지 출력
- [x] 숫자 입력 시 1 이상만 입력가능 
- [x] Study 생성 시 BOOK 또는 LECTURE가 빈칸일 경우 생성 안되는 오류
- [x] modify => update

# ETC
기타사항
