### ISSUE TITLE
ToDoList 리팩토링

### ISSUE THREAD

**Issue by Young998904** [likelion-backendschool/ZZANDI#107]
# Description

ToDoList 리팩토링

# Todo
- [ ] 보안 관련 부분
- [ ] 코드 관련 부분
- [x] header, footer 적용
