### ISSUE TITLE
스터디 신청 취소

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#113]
# Description

스터디 신청 취소

# Todo
- [x] 팀장이 대기자 목록에서 신청 취소
- [x] 팀원 - 신청한 스터디 목록 조회
- [x] 팀원이 신청했던 스터디 목록 중 신청 취소

# ETC
기타사항 : x
