### ISSUE TITLE
 study 관련 오류 수정

### ISSUE THREAD

**Issue by jootang2** [likelion-backendschool/ZZANDI#134]
# Description

study 관련 오류 수정

# Todo
- [x] Book 선택 하고 아무 입력 없을 경우 에러 수정
- [x] 스터디 태그 기능 수정 => 회원가입 시 설정되어 있는 관심사 중 1개 선택 가능하도록
- [x] 수정 시, ACCEPTED된 팀원보다 모집 인원 적게 설정하기 금지
- [x]  모집인원 2명으로
