### ISSUE TITLE
진도율 추천 & 개인 진도율 기록 기능 구현

### ISSUE THREAD

**Issue by Young998904** [likelion-backendschool/ZZANDI#138]
# Description

진도율 추천 & 개인 진도율 기록 기능 구현

# Todo
- [x] 진도율 바 디자인 결정
- [x] 진도율 추천 계산 방식 결정
- [x] 진도율 추천 바 기능 구현
- [x] 개인 진도율 기록 방식 결정
- [x] 진도율 기록 기능 구현
