### ISSUE TITLE
코드 리팩토링 (헤더 & 스터디)

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#160]
# Description

코드 리팩토링 (헤더 & 스터디)

# Todo
- [ ] 헤더에 필요한 user를 위해 model로 담아 넘겨주어야 하는 코드 개선
- [ ] 스터디 수정 및 삭제, 대표이미지 설정 시, 팀장만 가능하도록 체킹
- [ ] null 및 RuntimeException으로 예외 처리한 부분 StudyException으로 대체해보기

# ETC
기타사항 : X
