### ISSUE TITLE
스터디 리스트 페이지

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#163]
# Description

스터디 리스트 페이지

# Todo
- [ ] 스터디 리스트 페이징
- [ ] 스터디 상세 검색 기능
- [ ] 스터디 리스트 페이지 디자인

# ETC
기타사항 : x
