### ISSUE TITLE
달성률에 따른 zzandi 길이 기능

### ISSUE THREAD

**Issue by jootang2** [likelion-backendschool/ZZANDI#164]
# Description

달성률에 따른 zzandi 길이 기능 

# Todo
- [x] User 생성 시 기본적으로 15cm 잔디 생성
- [x] 공부기록을 등록 => 1cm 증가
- [x] 등록하지 않았을 시 => 1cm 감소
- [ ] 스터디 완료 시점에서 개인 달성률이 50% 이상 => 1cm 증가
- [ ] 스터디 완료 시점에서 개인 달성률이 75% 이상 => 2cm 증가
- [ ] 스터디 진행 중인 시점에서 탈퇴 시 => 2cm 감소
