### ISSUE TITLE
헤더 검색 추가 및 스터디 상세 css 수정

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#170]
# Description

검색칸 추가 및 스터디명 길이 제한

# Todo
- [ ] 헤더 검색란 추가
- [ ] 스터디명 max-width 수정
- [ ] 스터디원 수락 및 거절 관련 기능 오류 수정

# ETC
기타사항
