### ISSUE TITLE
메인 페이지 디자인

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#175]
# Description

메인 페이지 전체적인 디자인 수정이 목표!

# Todo
- [ ] 로그인 시, 내 스터디 리스트가 보이도록
- [ ] 신규 스터디 18개 리스트
- [ ] 추천 스터디 18개 리스트

# ETC
기타사항 : 투두리스트 사이드바는 고려하지 않음.
