### ISSUE TITLE
진도율 리팩토링

### ISSUE THREAD

**Issue by Young998904** [likelion-backendschool/ZZANDI#187]
# Description
스터디 상세 페이지 진도율 관련 리팩토링

# Todo
- [x] 추천 진도율 db 화 후 불필요한 변수 및 함수 제거
- [x] 스터디 테이블에 달성률 관련 컬럼 추가
- [x] 스터디 달성률 db 화 후 불필요한 변수 및 함수 제거
