### ISSUE TITLE
회원 프로필 페이지 디자인

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#195]
# Description

회원 프로필 페이지 디자인

# Todo
- [ ] 프로필 사진
- [ ] 닉네임
- [ ] 관심사
- [ ] 잔디 길이
- [ ] 참여 완료된 스터디 목록
- [ ] 참여 진행 중인 스터디 목록
- [ ] 프로필 페이지 내에서 회원 정보 수정 버튼 및 스터디 관리 버튼 생성 (해당 유저만 접근 가능하도록)

# ETC
기타사항 : x
