### ISSUE TITLE
첨부파일 기능 개선

### ISSUE THREAD

**Issue by dmdmk1** [likelion-backendschool/ZZANDI#200]
# Description

### 첨부파일 기능 개선 & 추가

# Todo
- [x] 파일 첨부 시 이미지 관련 파일만 허용
- [x] 첨부 파일 최대 용량 50MB
- [x] 게시글 작성 화면에서 첨부 파일 선택 삭제, 전체 삭제
- [x] 게시글 수정 화면에서 첨부파일 관리
- [x] 게시판, 댓글 화면 디자인 개선

# ETC
이게 마지막..?
