### ISSUE TITLE
마이 페이지 디자인

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#203]
# Description

마이 페이지 디자인

# Todo
- [ ] 회원 정보 수정 페이지(마이 페이지) 디자인
- [ ] 스터디 권한 위임 수락 및 스터디 취소 비동기 처리
- [ ] 스터디 관리 페이지 디자인

# ETC
기타사항
