### ISSUE TITLE
프로필 이미지 페이지 디자인

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#212]
# Description

프로필 이미지 페이지 디자인

# Todo
- [ ] 회원 프로필 적용 페이지 디자인
- [ ] 스터디 프로필 페이지 디자인 통일
- [ ] 스터디 프로필 페이지 cropper 적용
- [ ] 파일 삭제 시, deleteStatus 적용
- [ ] 스터디 생성 시, 대표 이미지 생성되도록

# ETC
기타사항
