### ISSUE TITLE
스터디 팀원 참가 신청

### ISSUE THREAD

**Issue by jyajoo** [likelion-backendschool/ZZANDI#66]
# Description

스터디 팀원 참가 신청

# Todo
- [ ] 팀원 엔티티 생성
- [ ] 참가 신청 시, 팀장에게 이메일 알람 전송
- [ ] 이미 신청했거나 팀원인 경우, 신청 버튼 비활성화
- [ ] 참가 수락 시, 팀원에게 이메일 알람 전송

# ETC
기타사항 : X
